# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: memory_service/memory.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'memory_service/memory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmemory_service/memory.proto\x12\x06memory\"$\n\x0eHistoryRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"@\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\"8\n\x0fHistoryResponse\x12%\n\x08messages\x18\x01 \x03(\x0b\x32\x13.memory.ChatMessage\"@\n\x0bSaveRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1f\n\x0cSaveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc4\x01\n\rMemoryService\x12=\n\nGetHistory\x12\x16.memory.HistoryRequest\x1a\x17.memory.HistoryResponse\x12\x38\n\x0bSaveMessage\x12\x13.memory.SaveRequest\x1a\x14.memory.SaveResponse\x12:\n\nDelHistory\x12\x16.memory.HistoryRequest\x1a\x14.memory.SaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_service.memory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYREQUEST']._serialized_start=39
  _globals['_HISTORYREQUEST']._serialized_end=75
  _globals['_CHATMESSAGE']._serialized_start=77
  _globals['_CHATMESSAGE']._serialized_end=141
  _globals['_HISTORYRESPONSE']._serialized_start=143
  _globals['_HISTORYRESPONSE']._serialized_end=199
  _globals['_SAVEREQUEST']._serialized_start=201
  _globals['_SAVEREQUEST']._serialized_end=265
  _globals['_SAVERESPONSE']._serialized_start=267
  _globals['_SAVERESPONSE']._serialized_end=298
  _globals['_MEMORYSERVICE']._serialized_start=301
  _globals['_MEMORYSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
