# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"2\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"0\n\x0c\x43hatResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x32H\n\x07\x43hatBot\x12=\n\nChatStream\x12\x14.chatbot.ChatRequest\x1a\x15.chatbot.ChatResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=26
  _globals['_CHATREQUEST']._serialized_end=76
  _globals['_CHATRESPONSE']._serialized_start=78
  _globals['_CHATRESPONSE']._serialized_end=126
  _globals['_CHATBOT']._serialized_start=128
  _globals['_CHATBOT']._serialized_end=200
# @@protoc_insertion_point(module_scope)
